server:
  port: 8081  # user-service'in portu

spring:
  application:
    name: user-service  # servis adı
  datasource:
    url: jdbc:postgresql://postgres:5432/userdb  # 'localhost' yerine 'postgres' yazıldı
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
